version: 2.1

jobs:
  # Python behave tests.
  python_behave: &python_behave_template
    docker:
      - image: circleci/python
    resource_class: small
    steps:
      - checkout
      - run:
          name: Setup Testing Environment
          command: pip install coverage codecov behave
      - run:
          name: Install Package
          command: pip install .[test]
      - run:
          command: coverage run -m behave
          name: Behave Tests with Coverage
      - run:
          command: codecov
          name: Upload Tests to CodeCov
  python_behave_3_5:
    <<: *python_behave_template
    docker:
      - image: circleci/python:3.5
  python_behave_3_6:
    <<: *python_behave_template
    docker:
      - image: circleci/python:3.6
  python_behave_3_7:
    <<: *python_behave_template
    docker:
      - image: circleci/python:3.7
  python_behave_3_8:
    <<: *python_behave_template
    docker:
      - image: circleci/python:3.8
  Documentation:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Install Package
          command: pip install .[docs]
      - run:
          command: make -C docs html
          name: Build Documention with Sphinx


workflows:
  main:
    jobs:
      - python_behave_3_5
      - python_behave_3_6
      - python_behave_3_7
      - python_behave_3_8
      - Documentation