version: 2.1

jobs:
  # celestial_tools behave tests.
  celestial_tools_behave: &celestial_tools_behave_template
    docker:
      - image: circleci/python
    resource_class: small
    steps:
      - checkout
      - run:
          name: Setup Testing Environment
          command: pip install coverage codecov behave
      - run:
          name: Install Package
          command: pip install .[test]
      - run:
          command: coverage run -m behave
          name: Behave Tests with Coverage
      - run:
          command: codecov
          name: Upload Tests to CodeCov
  celestial_tools_behave_3_5:
    <<: *celestial_tools_behave_template
    docker:
      - image: circleci/python:3.5
  celestial_tools_behave_3_6:
    <<: *celestial_tools_behave_template
    docker:
      - image: circleci/python:3.6
  celestial_tools_behave_3_7:
    <<: *celestial_tools_behave_template
    docker:
      - image: circleci/python:3.7
  celestial_tools_behave_3_8:
    <<: *celestial_tools_behave_template
    docker:
      - image: circleci/python:3.8

  celestial_tools_build:
    jobs:
      - celestial_tools_behave_3_5
      - celestial_tools_behave_3_6
      - celestial_tools_behave_3_7
      - celestial_tools_behave_3_8
      - Documentation
  # celestial_tools release.
  celestial_tools_deploy:

  # Documentation tests.
  Documentation:
    docker:
      - image: circleci/python
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install Package
          command: pip install .[docs]
      - run:
          command: make -C docs html
          name: Build Documention with Sphinx

  # Docker image release


workflows:
  celestial_tools:
    jobs:
      # Runs on all branches, but not tags.  Run the unit tests and generate the coverage reports
      - celestial_tools_build:
          filters:  # required since `celestial_tools_deploy` has tag filters AND requires `celestial_tools_build`
            tags:
              only: /.*/
      # Runs on tags that are formatted "celestial_tools_0.1.2", where the version in the tag exactly matches the version in the setup file
      - celestial_tools_deploy:
          requires:
            - celestial_tools_build
          filters:
            tags:
              only: /^celestial_tools_[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/