
version: 2.1

orbs:
  python: circleci/python@0.2.1
  codecov: codecov/codecov@1.0.5

jobs:
  behave_tests_with_coverage:
    docker:
      - image: circleci/python:3.8
      - image: circleci/python:3.7
      - image: circleci/python:3.6
      - image: circleci/python:3.5
    executor: python/default
    steps:
      - checkout
      - run:
          name: Setup Testing Environment
          command: pip install coverage codecov behave
      - run:
          name: Install Package
          command: pip install .[test,docs]
      - run:
          command: coverage run -m behave
          name: Behave Tests with Coverage
      - run:
          command: codecov
          name: Upload Tests to CodeCov

workflows:
  main:
    jobs:
      - behave_tests_with_coverage