version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: pseudodesign/celestial-dev:0.0.1
    executor: python/default
    steps:
      - checkout
      - run:
          command: behave
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
