version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  behave_tests:
    docker:
      - image: pseudodesign/celestial-dev:0.0.1
    executor: python/default
    steps:
      - checkout
      - run:
          command: behave
          name: Behave Tests

workflows:
  main:
    jobs:
      - behave_tests
