version: 2.1

jobs:
  python_behave_template: &python_behave_template
    steps:
      - checkout
      - run:
          name: Setup Testing Environment
          command: pip install coverage codecov behave
      - run:
          name: Install Package
          command: pip install .[test,docs]
      - run:
          command: coverage run -m behave
          name: Behave Tests with Coverage
      - run:
          command: codecov
          name: Upload Tests to CodeCov
  python_behave_3.5:
    <<: *python_behave_template
    docker:
      - image: circleci/python:3.5
  python_behave_3.6:
    <<: *python_behave_template
    docker:
      - image: circleci/python:3.6
  python_behave_3.7:
    <<: *python_behave_template
    docker:
      - image: circleci/python:3.7
  python_behave_3.8:
    <<: *python_behave_template
    docker:
      - image: circleci/python:3.8


workflows:
  main:
    jobs:
      - python_behave_3.5
      - python_behave_3.6
      - python_behave_3.7
      - python_behave_3.8