version: 2.1

orbs:
  python: circleci/python@0.2.1
  codecov: codecov/codecov@1.0.6

jobs:
  behave_tests:
    docker:
      - image: pseudodesign/celestial-dev:0.0.1
    executor: python/default
    steps:
      - checkout
      - run:
          command: behave
          name: Behave Tests
  behave_tests_with_coverage:
    docker:
      - image: pseudodesign/celestial-dev:0.0.2
    executor: python/default
    steps:
      - checkout
      - run:
          name: Setup Testing Environment
          command: |
            pip install 'coverage'
      - run:
          command: |
            coverage run -m behave
            coverage report
            coverage html
          name: Behave Tests
      - codecov/upload:
          file: .coverage


workflows:
  main:
    jobs:
      - behave_tests_with_coverage
